version: "3"

services:
  cookbook_web:
    image: cis1880-cookbook:v1
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - cookbook_redis

  cookbook_redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
