name: Cookbook

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies and Run Tests
      run: |
        python -m pip install --upgrade pip
        cd web
        pip install poetry
        poetry install
        poetry run pytest
    - name: Run linter
      run: |
        cd web
        poetry install
        poetry run flake8
