apiVersion: batch/v1
kind: CronJob
metadata:
  name: aggregator
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: aggregator
              image: cis1880-cookbook-aggregator:v1
              command: ["python", "main.py"]
          restartPolicy: Never
